# Generated by Django 5.2.4 on 2025-07-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('journal_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='publications_files/')),
            ],
        ),
    ]
