# Generated by Django 5.2.4 on 2025-07-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
