# Generated by Django 5.2.4 on 2025-07-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portm', '0002_publication_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='journal_name',
            new_name='journal',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='year',
            new_name='published_year',
        ),
    ]
